
# FUTUREWORK: consistency: rename sft_ variables to sftd_ (currently some things are named sft and other sftd which is confusing)
#
- name: download SFTD artifact
  get_url:
    url: "{{ sft_artifact_file_url }}"
    dest: "{{ sft_artifact_target_path }}"
    # sha256sum:

- name: unpacking artifact
  unarchive:
    remote_src: yes
    src: "{{ sft_artifact_target_path }}"
    dest: '/tmp/'
    list_files: yes
  register: unpacked

- name: copying SFT executable to right location
  copy:
    src: "{{ unpacked.dest }}{{ unpacked.files[0] }}"
    remote_src: yes
    dest: "{{ sftd_bin_path }}"
  register: binary_sftd

- name: ensuring executable state
  file:
    path: "{{ sftd_bin_path }}"
    state: 'file'
    mode: '755'


- name: installing core-dump components
  apt:
    state: present
    update_cache: yes
    name:
      - systemd-coredump
  when:
    - systemd_coredump_enabled | bool


# docs: https://www.nginx.com/resources/wiki/start/topics/tutorials/install/
- name: adding key for nginx's apt repositpry
  apt_key:
    id: 'ABF5BD827BD9BF62'
    url: "https://nginx.org/keys/nginx_signing.key"
    state: present

- name: adding nginx's apt repositpry
  apt_repository:
    repo: "deb https://nginx.org/packages/{{ ansible_facts.distribution | lower }}/ {{ ansible_distribution_release | lower }} nginx"
    state: present
    update_cache: yes

- name: installing nginx packages
  apt:
    state: present
    name:
      - nginx


- name: adding certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
    update_cache: yes
  when:
    - certbot_enabled

- name: installing certbot
  apt:
    state: present
    name:
      - certbot
  when:
    - certbot_enabled


- name: installing ufw
  apt:
    state: present
    name:
      - ufw
